name: Run Apps Sequentially from Input

on:
  workflow_dispatch:
    inputs:
      apps:
        description: "Comma-separated list of applications"
        required: true
        default: "app1,app2,app3,app4,app5"

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - name: Parse input and create JSON array
        id: set
        run: |
          echo "Input apps: ${{ github.event.inputs.apps }}"
          apps_json=$(echo '${{ github.event.inputs.apps }}' | jq -R 'split(",")')
          echo "matrix={\"app\": $apps_json}" >> $GITHUB_OUTPUT

  run-apps:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      max-parallel: 1  # Force sequential execution
    steps:
      - name: Run ${{ matrix.app }}
        run: |
          echo "Running application: ${{ matrix.app }}"
          # Simulate some command
          ./run-${{ matrix.app }}.sh || echo "${{ matrix.app }} failed"
