name: Matrix Sequential Execution

on:
  workflow_dispatch:

jobs:
  run-apps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [app1, app2, app3, app4, app5]
      max-parallel: 1  # 👈 This ensures jobs run one-by-one
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run matrix app
        run: |
          echo "Running ${{ matrix.app }}"
          # Simulate app logic
          ./run-${{ matrix.app }}.sh || echo "${{ matrix.app }} failed"
