name: Run Apps Sequentially from Input

on:
  workflow_dispatch:
    inputs:
      apps:
        description: "Comma-separated list of applications"
        required: true
        default: "app1,app2,app3,app4,app5"

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - name: Convert comma-separated input to matrix JSON
        id: set
        run: |
          APPS="${{ github.event.inputs.apps }}"
          echo "Input: $APPS"
          # Convert to JSON array
          MATRIX_JSON=$(echo "$APPS" | tr ',' '\n' | jq -R . | jq -s '{app: .}')
          echo "Parsed matrix: $MATRIX_JSON"
          # Use printf to avoid trailing newline which breaks set-output
          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT

  run-apps:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      max-parallel: 1
    steps:
      - name: Run ${{ matrix.app }}
        run: |
          echo "Running application: ${{ matrix.app }}"
          # Replace this with your actual script or command
          echo "./run-${{ matrix.app }}.sh"
